version: "3.9"
services:
  api:
    build:
      context: ..
      dockerfile: ComandAppApi\Dockerfile
    ports:
      - "5000:80"

  db:
    image: mcr.microsoft.com/mssql/server
    deploy:
        resources:
            limits:
              memory: 4096M
            reservations:
              memory: 2048M
    environment:
       SA_PASSWORD: "1q2w3e4r@#$$"
       ACCEPT_EULA: "Y"
       MSSQL_PID: Express
    ports:
     - "1433:1433"